### ISSUE TITLE
`-output` option is not working

### ISSUE THREAD

**Issue by NotoriousRebel** [projectdiscovery/asnmap#176]
Take for example:

`asnmap -a AS20940 -j`

vs

`asnmap -a AS20940 -j -o test.json`

The latter of the two does not work, it's not a  big deal as can just redirect stdout to a file but ideally `-o` should write the results to a file.

**Comment by NotoriousRebel** [comment]
Also not sure if this is  intended but the JSON is all in one line missing any delimiters which is fine if that's how it's suppose to be but differs from how every other ProjectDiscovery tool (httpx, tlsx, dnsx, nuclei, etc...) outputs JSON. 

Take for example:

`asnmap -a AS20940 -j > test.json`

Let's say I wanted to parse that JSON

```py
import json
fp = open('test.json', 'r')
lines = json.load(fp)
fp.close()
```
You would get the following error:

```Traceback (most recent call last):
  File "test.py", line 350, in <module>
    lines = json.load(fp)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 175 (char 174)
```
This is due to as aforementioned the lack of delimters in the results, while yes you could parse it with [pandas](https://stackoverflow.com/questions/30088006/loading-a-file-with-more-than-one-line-of-json-into-pandas) you shouldn't need to install a 3rd party library to just parse JSON... Ideally this JSON should follow suit and be uniform with how every other ProjectDiscovery tool outputs JSON.
